<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ForgeDotNet.Application\ForgeDotNet.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Container\RunnerHost\**\*.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
