// <auto-generated />
using System;
using ForgeDotNet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeDotNet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    [Migration("20260725141251_InitialLocalProfile")]
    partial class InitialLocalProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LocalProfileRecord", b =>
                {
                    b.Property<int>("ProfileSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAcceptedLearningContract")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionalGoal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyAvailableHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileSlot");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.ToTable("LocalProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
