// <auto-generated />
using System;
using ForgeDotNet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeDotNet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    [Migration("20260725224303_DiagnosticEvaluations")]
    partial class DiagnosticEvaluations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrozenRubricJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RubricVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("DiagnosticEvaluations", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticResponseRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOptionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "QuestionId");

                    b.ToTable("DiagnosticResponses", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("BankVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentSectionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrozenPlanJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionDeadlineUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionStartedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionStatusesJson")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "StartedAtUtc");

                    b.ToTable("DiagnosticSessions", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LessonBookmarkRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId");

                    b.ToTable("LessonBookmarks", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LessonNoteRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId");

                    b.ToTable("LessonNotes", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LessonReadingActivityRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId", "ActivityId");

                    b.ToTable("LessonReadingActivities", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LocalProfileRecord", b =>
                {
                    b.Property<int>("ProfileSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAcceptedLearningContract")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionalGoal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyAvailableHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileSlot");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.ToTable("LocalProfiles", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.DiagnosticSessionRecord", null)
                        .WithOne()
                        .HasForeignKey("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticResponseRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.DiagnosticSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
