// <auto-generated />
using System;
using ForgeDotNet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeDotNet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    partial class ForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DebugCorrectionAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedTests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Sequence")
                        .IsUnique();

                    b.ToTable("DebugCorrectionAttempts", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DebugLabActivityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Breakpoint")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CallStack")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationJson")
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fix")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hypotheses")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Locals")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prevention")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolutionViewedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symptom")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Test")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Watch")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "ScenarioId")
                        .IsUnique();

                    b.ToTable("DebugLabActivities", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrozenRubricJson")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RubricVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId");

                    b.ToTable("DiagnosticEvaluations", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticResponseRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOptionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "QuestionId");

                    b.ToTable("DiagnosticResponses", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("BankVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentSectionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrozenPlanJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionDeadlineUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionStartedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionStatusesJson")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "StartedAtUtc");

                    b.ToTable("DiagnosticSessions", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.ExamAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssistanceDeclared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletionReason")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadlineUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawCommitment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrozenItemsJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PassingScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportJson")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "StartedAtUtc");

                    b.HasIndex("ProfileId", "Status");

                    b.ToTable("ExamAttempts", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.ExamSubmissionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HiddenFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId")
                        .IsUnique();

                    b.HasIndex("AttemptId", "ItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("ExamSubmissions", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LessonBookmarkRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId");

                    b.ToTable("LessonBookmarks", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LessonNoteRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId");

                    b.ToTable("LessonNotes", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LessonReadingActivityRecord", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "LessonId", "ActivityId");

                    b.ToTable("LessonReadingActivities", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.LocalProfileRecord", b =>
                {
                    b.Property<int>("ProfileSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAcceptedLearningContract")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionalGoal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyAvailableHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileSlot");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.ToTable("LocalProfiles", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.MasteryProjectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrozenPolicyJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "PolicyRevision", "EvidenceRevision")
                        .IsUnique();

                    b.ToTable("MasteryProjections", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeActivityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonalExplanation")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostSolutionCompletedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionViewedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantSubmission")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("PracticeActivities", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSerious")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualCheckDeclared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualVerificationNotes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionText")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Sequence")
                        .IsUnique();

                    b.ToTable("PracticeAttempts", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeHintUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Level")
                        .IsUnique();

                    b.ToTable("PracticeHintUsages", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeLearningAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedTests")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionFingerprint")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "ObservedAtUtc");

                    b.ToTable("PracticeLearningAttempts", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeReflectionRecord", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdgeCases")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reformulation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityId");

                    b.ToTable("PracticeReflections", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.ReviewAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnsweredAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMasteryEligible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextDueOn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousDueOn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseFingerprint")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReviewItemId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("ReviewAttempts", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.ReviewItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanProduceMasteryEvidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoicesJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentIntervalIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("DueOn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedAnswer")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastReviewedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceItemId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceItemVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOccurredAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "DueOn", "IsActive");

                    b.HasIndex("ProfileId", "SourceKey", "SourceRevision", "PolicyRevision")
                        .IsUnique();

                    b.ToTable("ReviewItems", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.SqlLearningAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiagnosticId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ElapsedMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryFingerprint")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ValidationPassed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ValidationRequested")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticId")
                        .IsUnique();

                    b.HasIndex("ProfileId", "ObservedAtUtc");

                    b.ToTable("SqlLearningAttempts", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.WeeklyPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedAtUtc")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurriculumId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurriculumRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurriculumVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DiagnosticSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetWeeklyHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticSessionId");

                    b.HasIndex("ProfileId", "DiagnosticSessionId", "Version")
                        .IsUnique();

                    b.ToTable("WeeklyPlans", (string)null);
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DebugCorrectionAttemptRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.DebugLabActivityRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.DiagnosticSessionRecord", null)
                        .WithOne()
                        .HasForeignKey("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.DiagnosticResponseRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.DiagnosticSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.ExamSubmissionRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.ExamAttemptRecord", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeAttemptRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.PracticeActivityRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeHintUsageRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.PracticeActivityRecord", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.PracticeReflectionRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.PracticeActivityRecord", null)
                        .WithOne()
                        .HasForeignKey("ForgeDotNet.Infrastructure.Persistence.PracticeReflectionRecord", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.ReviewAttemptRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.ReviewItemRecord", null)
                        .WithMany()
                        .HasForeignKey("ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeDotNet.Infrastructure.Persistence.WeeklyPlanRecord", b =>
                {
                    b.HasOne("ForgeDotNet.Infrastructure.Persistence.DiagnosticEvaluationRecord", null)
                        .WithMany()
                        .HasForeignKey("DiagnosticSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
